config/routes.rb
Oscurrency::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :person_sessions
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :member_preferences
  resources :neighborhoods

  # XXX in 2.3.x, this was easier -> map.resources :transacts, :as => "transacts/:asset"
  get    "transacts(/:asset)(.:format)"          => "transacts#index",   :as => 'transacts'
  get    "transacts(/:asset)/new"      => "transacts#new",     :as => 'new_transact'
  get    "transacts(/:asset)/:id(.:format)"      => "transacts#show",    :as => 'transact'
  post   "transacts(/:asset)(.:format)"          => "transacts#create",  :as => 'transacts'
  #get    "transacts/[:asset]/:id/edit" => "transacts#edit",    :as => 'edit_transact'
  #put    "transacts/[:asset]/:id"      => "transacts#update",  :as => 'transact'
  delete "transacts(/:asset)/:id(.:format)"      => "transacts#destroy", :as => 'transact'

  resources :groups, :shallow => true do
    member do
      post :join
      post :leave
      get :exchanges
      get :members
      get :graphs
      get :photos
      post :new_photo
      post :save_photo
      delete :delete_photo
    end
    resources :memberships
    resources :reqs
    resources :offers
    resource :forum
  end

  resources :bids
  resources :reqs do
    member do 
      post :deactivate
    end
    resources :bids
  end

  resources :offers
  resources :categories

  resources :memberships do
    member do
      delete :unsuscribe
      post :suscribe
    end
  end

  resources :searches
  resources :activities
  resources :connections
  resources :photos
  resources :messages do
    collection do
      get :sent
      get :trash
      get :recipients
    end
    member do
      get :reply
      put :undestroy
    end
  end
  resources :people do
    member do
      get :verify_email
      get :su
      get :common_contacts
      get :groups
      get :admin_groups
    end
    resources :messages
    resources :accounts
    resources :exchanges
    resources :addresses
    resources :photos
    resources :connections
  end

  match 'people/verify/:id' => 'people#verify_email'

  resources :forums do
    resources :topics do
      resources :posts
    end
  end
  match '/signup' => 'people#new', :as => :signup
  match '/login' => 'person_sessions#new', :as => :login
  match '/logout' => 'person_sessions#destroy', :as => :logout
  match '/refreshblog' => 'feed_posts#refresh_blog', :as => :refreshblog
  match '/about' => 'home#about', :as => :about
  match '/practice' => 'home#practice', :as => :practice
  match '/steps' => 'home#steps', :as => :steps
  match '/questions' => 'home#questions', :as => :questions
  match '/contact' => 'home#contact', :as => :contact
  match '/agreement' => 'home#agreement', :as => :agreement
  resources :oauth_clients
  match '/oauth/authorize' => 'oauth#authorize', :as => :authorize
  match '/oauth/token' => 'oauth#token', :as => :token
  match '/oauth/request_token' => 'oauth#request_token', :as => :request_token
  match '/oauth/access_token' => 'oauth#access_token', :as => :access_token
  match '/oauth/test_request' => 'oauth#test_request', :as => :test_request
  match '/oauth/scopes' => 'transacts#scopes', :as => :scopes
  match '/oauth/revoke' => 'oauth#revoke', :as => :revoke
  match '/oauth' => 'oauth#index', :as => :oauth
  match '/about_user' => 'transacts#about_user', :as => :about_user
  match '/user_info' => 'transacts#user_info', :as => :user_info
  match '/wallet' => 'transacts#wallet', :as => :wallet
  match '/.well-known/host-meta' => 'home#host_meta', :as => :host_meta
  match '/home/show/:id' => 'home#show'
  root :to => 'home#index'
  match '/' => 'home#index', :as => :home
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController

  skip_before_filter :require_activation, :only => :verify_email
  skip_before_filter :admin_warning, :only => [ :show, :update ]
  #before_filter :login_or_oauth_required, :only => [ :index, :show, :edit, :update ]
  before_filter :login_required, :only => [ :index, :show, :edit, :update ]
  before_filter :correct_person_required, :only => [ :edit, :update ]
  before_filter :setup_zips, :only => [:index, :show]

  def index
    @zipcode = ""
    if global_prefs.zipcode_browsing? && params[:zipcode]
      @people = Person.
        with_zipcode(params[:zipcode]).
        mostly_active.
        by_name.
        paginate(:page => params[:page], :per_page => RASTER_PER_PAGE)
      @zipcode = "(#{params[:zipcode]})"
    else
      if params[:sort]
        if "alpha" == params[:sort]
          @people = Person.
            by_first_letter.
            mostly_active.
            paginate(:page => params[:page], :per_page => RASTER_PER_PAGE, :group_by => "first_letter")
          @people.add_missing_links(('A'..'Z').to_a)
        end
      else
        @people = Person.
          by_newest.
          mostly_active.
          paginate(:page => params[:page], :per_page => RASTER_PER_PAGE)
      end
    end

    respond_to do |format|
      format.html
    end
  end

  def show
    person_id = ( 0 == params[:id].to_i ) ? current_person.id : params[:id]
    @person = Person.find(person_id)
    unless @person.active? || current_person.admin? || (global_prefs.whitelist? && current_person.activator?)
      flash[:error] = t('error_person_inactive')
      redirect_to home_url and return
    end
    if logged_in?
      @groups = current_person == @person ? @person.groups : @person.groups_not_hidden
    end
    respond_to do |format|
      format.html
      if current_person == @person
        format.json { render :json => @person.as_json( :methods => :icon, :only => [:id, :name, :description, :created_at, :identity_url,:icon], :include => {:accounts => {:only => [:balance_with_initial_offset,:group_id]}, :groups => {:only => [:id,:name]}, :own_groups => { :methods => [:icon,:thumbnail], :only => [:id,:name,:mode,:icon,:thumbnail] } }) }
        format.xml { render :xml => @person.to_xml( :methods => :icon, :only => [:id, :name, :description, :created_at, :identity_url,:icon], :include => {:accounts => {:only => [:balance_with_initial_offset,:group_id]}, :groups => {:only => [:id,:name]}, :own_groups => { :methods => [:icon,:thumbnail], :only => [:id,:name,:mode,:icon,:thumbnail] }}) }
      else
        format.json { render :json => @person.as_json( :methods => :icon, :only => [:id, :name, :description, :created_at, :identity_url,:icon], :include => {:accounts => {:only => [:balance_with_initial_offset,:group_id]}, :groups_not_hidden => {:only => [:id,:name]}}) }
        format.xml { render :xml => @person.to_xml( :methods => :icon, :only => [:id, :name, :description, :created_at, :identity_url,:icon], :include => {:accounts => {:only => [:balance_with_initial_offset,:group_id]}, :groups_not_hidden => {:only => [:id,:name]}}) }
      end
    end
  end

  def new
    @body = "register single-col"
    @person = Person.new
    @all_categories = Category.find(:all, :order => "parent_id, name").sort_by { |a| a.long_name }
    @all_neighborhoods = Neighborhood.find(:all, :order => "parent_id, name").sort_by { |a| a.long_name }
    respond_to do |format|
      format.html
    end
  end

  def create
    @person = Person.new(params[:person])
    @person.email_verified = false if global_prefs.email_verifications?
    @person.save do |result|
      respond_to do |format|
        if result
          if global_prefs.can_send_email? && !global_prefs.new_member_notification.blank?
            after_transaction { PersonMailerQueue.registration_notification(@person) }
          end
          if global_prefs.email_verifications?
            @person.deliver_email_verification!
            flash[:notice] = t('notice_thanks_for_signing_up_check_email')
            format.html { redirect_to(home_url) }
          else
            # XXX self.current_person = @person
            flash[:notice] = t('notice_thanks_for_signing_up')
            format.html { redirect_to(home_url) }
          end
        else
          @body = "register single-col"
          @all_categories = Category.find(:all, :order => "parent_id, name").sort_by { |a| a.long_name }
          @all_neighborhoods = Neighborhood.find(:all, :order => "parent_id, name").sort_by { |a| a.long_name }
          format.html { render :action => 'new' }
        end
      end
    end
  rescue ActiveRecord::StatementInvalid
    # Handle duplicate email addresses gracefully by redirecting.
    redirect_to home_url
  rescue ActionController::InvalidAuthenticityToken
    # Experience has shown that the vast majority of these are bots
    # trying to spam the system, so catch & log the exception.
    warning = "ActionController::InvalidAuthenticityToken: #{params.inspect}"
    logger.warn warning
    redirect_to home_url
  end

  def verify_email
    person = Person.find_using_perishable_token(params[:id])
    unless person
      flash[:error] = t('error_invalid_email_verification_code')
      redirect_to home_url
    else
      person.email_verified = true
      person.save!
      if Person.global_prefs.whitelist?
        flash[:success] = t('success_email_verified_whitelist')
      else
        flash[:success] = t('success_email_verified')
      end
      redirect_to login_url
    end
  end

  def edit
    logger.info "XXX id: #{params[:id]}"
    @all_categories = Category.find(:all, :order => "parent_id, name").sort_by { |a| a.long_name }
    @all_neighborhoods = Neighborhood.find(:all, :order => "parent_id, name").sort_by { |a| a.long_name }
    respond_to do |format|
      format.html
    end
  end

  def update
    if cancel?
      flash[:notice] = "#{CGI.escapeHTML @person.display_name} " + t('cancelled')
      redirect_to person_path(@person)
      return
    end

    unless(params[:task].blank?)
      @person.toggle!(params[:task])
      if 'deactivated' == params[:task]
        @person.update_attributes!(:sponsor => current_person)
      end
      flash[:success] = "#{CGI.escapeHTML @person.display_name} " + t('success_updated')
      redirect_to person_path(@person)
      return
    end

    case params[:type]
    when 'info_edit'
      respond_to do |format|
        if @person.update_attributes(params[:person])
          flash[:success] = t('success_profile_updated')
          format.html { redirect_to(@person) }
        else
          @all_categories = Category.find(:all, :order => "parent_id, name").sort_by { |a| a.long_name }
          @all_neighborhoods = Neighborhood.find(:all, :order => "parent_id, name").sort_by { |a| a.long_name }
          format.html { render :action => "edit" }
        end
      end
    when 'password_edit'
      if global_prefs.demo?
        flash[:error] = t('error_password_cant_be_changed')
        redirect_to @person and return
      end
      respond_to do |format|
        if @person.change_password?(params[:person])
          flash[:success] = t('success_password_changed')
          format.html { redirect_to(@person) }
        else
          @all_categories = Category.find(:all, :order => "parent_id, name").sort_by { |a| a.long_name }
          @all_neighborhoods = Neighborhood.find(:all, :order => "parent_id, name").sort_by { |a| a.long_name }
          format.html { render :action => "edit" }
        end
      end
      #when 'openid_edit'
    else
      @person.attributes = params[:person]
      @person.save do |result|
        respond_to do |format|
          if result
            flash[:success] = t('success_profile_updated')
            format.html { redirect_to(@person) }
          else
            @all_categories = Category.find(:all, :order => "parent_id, name").sort_by { |a| a.long_name }
            @all_neighborhoods = Neighborhood.find(:all, :order => "parent_id, name").sort_by { |a| a.long_name }
            format.html { render :action => "edit" }
          end
        end
      end
    end
  end

  def common_contacts
    @person = Person.find(params[:id])
    @common_contacts = @person.common_contacts_with(current_person,
                                                    params[:page])
    respond_to do |format|
      format.html
    end
  end

  def groups
    @person = Person.find(params[:id])
    @groups = current_person == @person ? @person.groups : @person.groups_not_hidden

    respond_to do |format|
      format.html
    end
  end

  def admin_groups
    @person = Person.find(params[:id])
    @groups = @person.own_groups
    render :action => :groups
  end

  def su
    @person = Person.find(params[:id])
    if can?(:su, @person)
      @person_session = PersonSession.create(@person)
    else
      flash[:error] = t('error_admin_access_required')
    end

    respond_to do |format|
      format.html { redirect_to(@person) }
    end
  end

  private

    def setup_zips
      @zips = []
      @zips = Address.find(:all).map {|a| a.zipcode_plus_4}
      @zips.uniq!
      @zips.delete_if {|z| z.blank?}
      @zips.sort!
    end

    def correct_person_required
      @person = Person.find(params[:id])
      unless(params[:task].blank?)
        can_change_status = case params[:task]
        when 'deactivated'
          current_person.admin? || (global_prefs.whitelist? && current_person.activator?)
        when 'activator'
          current_person.admin?
        end
        flash[:error] = t('error_admin_access_required') unless can_change_status
        redirect_to person_path(@person) unless can_change_status
      else
        redirect_to home_url unless ( current_person.admin? or Person.find(params[:id]) == current_person )
      end
    end

    def cancel?
      params["commit"] == t('button_cancel');
    end
end

app/helpers/people_helper.rb
module PeopleHelper

  def message_links(people)
    people.map { |p| email_link(p)}
  end

  # Return a person's image link.
  # The default is to display the person's icon linked to the profile.
  def image_link(person, options = {})
    link = options[:link] || person
    image = options[:image] || :icon
    image_options = { :title => h(person.display_name), :alt => h(person.display_name) }
    unless options[:image_options].nil?
      image_options.merge!(options[:image_options]) 
    end
    link_options =  { :title => h(person.display_name) }
    unless options[:link_options].nil?                    
      link_options.merge!(options[:link_options])
    end
    content = image_tag(person.send(image), image_options)
    # This is a hack needed for the way the designer handled rastered images
    # (with a 'vcard' class).
    if options[:vcard]
      content = %(#{content}#{content_tag(:span, h(person.display_name), 
                                                 :class => "fn" )})
    end
    link_to(content, link, link_options)
  end

  # Link to a person (default is by name).
  def person_link(text, person = nil, html_options = nil)
    if person.nil?
      person = text
      text = person.display_name
    elsif person.is_a?(Hash)
      html_options = person
      person = text
      text = person.display_name
    end
    # We normally write link_to(..., person) for brevity, but that breaks
    # activities_helper_spec due to an RSpec bug.
    link_to(h(text), person, html_options)
  end
    
  private
    
    # Make captioned images.
    def captioned(images, captions)
      images.zip(captions).map do |image, caption|
        markaby do
          image << div { caption }
        end
      end
    end
end

app/views/people/_groups.html.erb
<%- unless groups.empty? -%>
  <h2><%= title %></h2>
  <ul class="grid contacts small">
    <%- groups.each do |group| -%>
      <li class="vcard">
        <%= group_image_link(group, :image_options => { :class => "photo fn" },
                                :link_options =>  { :class => "url" }) %>
      </li>
    <%- end -%>
    <li class="more">
      <%= link_to "#{t('see_all') + " &raquo;"}".html_safe, 
          link == "admin" ? 
              admin_groups_person_path(@person) : groups_person_path(@person) %>
    </li>
  </ul>
<%- end -%>

app/views/people/common_contacts.html.erb
<%= column_div :type => :primary do -%>
<h2>Common contacts with <%= @person.display_name %></h2>
<% unless @common_contacts.empty? -%>
  <%= will_paginate(@common_contacts) %>
  <ul class="list people">
    <%= render :partial => 'people/person',
               :collection => @common_contacts %>
  </ul>
  <%= will_paginate(@common_contacts) %>
<% else %>
  <h2>No contacts in common</h2>
<% end -%>

<%- end -%>

<%= column_div :type => :secondary do -%>
<%- end -%>

app/views/people/edit.html.erb
<%= column_div :type => :primary do -%>
  <h2><%= t('people.edit.header') %></h2>

  <div id="profile_edit">

  <h3><%= t('people.edit.personal_details') %></h3>

    <%= error_messages_for :person %>
    <%= form_for @person do |f| %>
      <div class="form_row">
        <label for="person_name"><%= t('people.edit.name') %></label>
        <%= f.text_field :name, :maxlength => Person::MAX_NAME %>
      </div>
      <div class="form_row">
          <label for="person_phoneprivacy"
            class="checkbox"><%= t('people.edit.share_phone_number') %></label>
          <%= f.check_box :phoneprivacy %>
      </div>
      <div class="form_row">
        <label for="person_phone"><%= image_tag "icons/phone.gif", :class => "icon", :alt => "Phone" %> <%= t('people.edit.phone') %></label>
        <%= f.text_field :phone %>
      </div>

  <div class="form_row full">
        <label for="person_categories"><%= t('people.edit.services_offered') %>
        </label>
        <span class="categoryAdd"><%= link_to t('people.edit.add_new_category'), new_category_path %></span>
        <%= render :partial => "shared/select_categories", :locals => { :model_name => 'person' } %>
  </div>

  <div class="form_row full">
        <label for="person_neighborhoods"><%= t('people.edit.neighborhood') %>
        </label>
        <%= render :partial => "shared/select_neighborhoods", :locals => { :model_name => 'person' } %>
  </div>

      <div class="form_row">
        <label for="person_description"><%= t('people.edit.description') %>
        </label>

        <%- unless @preview.nil? %>
          <%= display @preview %>
        <%- end -%>
        <%= f.text_area :description %>
      </div>

      <%= render :partial => 'language', :locals => {:f => f} %>

      <div class="form_row">
        <label for="person_email"><%= t('people.edit.email') %></label>
        <%= f.email_field :email %>
      </div>

      <div class="form_row">
        <label for="person_web_site_url"><%= t('people.edit.web_site_url') %></label>
        <%= f.text_field :web_site_url %>
      </div>

      <%- if global_prefs.email_notifications? -%>

        <br />

        <h3><%= t('people.edit.email_notification_preferences') %></h3>

        <p>
          <%= t('people.edit.email_notification_note') %>
        </p>


        <div class="form_row">
          <p>
          <label for="message_notifications"
                 class="checkbox"><%= t('people.edit.messages') %></label>
          <%= f.check_box :message_notifications %>
          </p>
          <p>
            <%= f.check_box :broadcast_emails %>
            <label for="broadcast_emails"
                 class="checkbox"><%= t('people.edit.broadcast_emails') %></label>
          </p>
          <p>
          <label for="broadcast_emails"
                 class="checkbox"><%= t('people.edit.broadcast_emails') %></label>
          <%= f.check_box :broadcast_emails %>
          </p>
        </div>
      <%- end -%>

      <div class="form_row">
        <p>
        <label for="org"
               class="checkbox"><%= t('people.edit.business_account') %>:</label>
        <%= f.check_box :org %>
        </p>
      </div>

      <div id="business_details">
        <h3><%= t('people.edit.business_details') %></h3>

        <div class="form_row">
          <label for="person_business_name"><%= t('people.edit.business_name') %></label>
          <%= f.text_field :business_name %>
        </div>

        <div class="form_row">
          <label for="person_legal_business_name"><%= t('people.edit.legal_business_name') %></label>
          <%= f.text_field :legal_business_name %>
        </div>

        <div class="form_row">
          <label for="person_title"><%= t('people.edit.title') %></label>
          <%= f.text_field :title %>
        </div>

        <div class="form_row full">
          <label for="person_business_type"><%= t('people.edit.business_type') %>
          </label>
          <%= render :partial => "shared/select_business_type", :locals => { :model_name => 'person' } %>
        </div>

      </div>

      <br />

      <div class="form_row">
        <%= f.submit t('button_update'), :class => "button" %>
        <%= f.submit t('button_cancel'), :id => "cancel", :class => "button" %>
      </div>
      <input type="hidden" name="type" value="info_edit" />
  <% end %>

  <br />

  <h3><%= t('people.edit.photos') %></h3>

    <% if @person.photos.empty? %>
      <%= image_tag @person.thumbnail %>
    <% else %>
    <table>
      <% @person.sorted_photos.collect_every(N_COLUMNS) do |row| %>
      <tr>
      <% row.each do |photo| %>
        <td  style="padding-left: 1em;">
          <%= image_tag photo.public_filename(:thumbnail) %>
        </td>
      <% end %>
      </tr>
      <tr>
        <% row.each do |photo| %>
        <td style="padding-left: 1em;">
          <% if photo.primary? %>
            primary
          <% else %>
            <%= link_to t('button_select'), photo_path(photo),
                                          :method => :put %>
          <% end %>
          |
          <%= link_to image_tag("icons/close.gif"), photo_path(photo),
                                               :method => :delete %>
        </td>
        <% end %>
      </tr>
      <% end %>
    </table>
    <% end %>
    <br />
    <%= link_to t('people.edit.add_a_photo'), new_photo_path, :class => 'button' %>
  </div>

  <br />
  <h3><%= t('people.edit.addresses') %></h3>
  <%= render :partial => 'address', :collection => @person.addresses %>
  <div class="status-btn" style="float: left">
    <input type="button" name="update" class="button" value="<%= t('people.edit.add_address') %>" id="update-submit" onclick="document.location='<%= new_person_address_path(@person) %>';" />
  </div>
  <br />
<%- end -%>

<%= column_div :type => :secondary do -%>
  <h2><%= t('people.edit.change_your_password') %></h2>

  <%= form_for @person, :html => { :id => "change_password" } do |f| %>

    <div class="form_row">
      <label for="password"><%= t('people.edit.new_password') %></label>
      <%= f.password_field :password,
                           :size => 34,
                           :maxlength => Person::MAX_PASSWORD %>
    </div>

    <div class="form_row">
      <label for="password_confirmation"><%= t('people.edit.confirm_password') %></label>
      <%= f.password_field :password_confirmation,
                           :size => 34,
                           :maxlength => Person::MAX_PASSWORD,
                           :value => "" %>
    </div>
    <div class="form_row">
      <%= submit_tag t('people.edit.change_password'), :class => "button" %>
    </div>
    <input type="hidden" name="type" value="password_edit" />
  <% end %>

  <h2>OpenID</h2>

  <%= form_for @person, :html => { :id => "openid" } do |f| %>
    <div class="form_row">
      <label for="openid_identifier"><%= t('people.edit.openid_identifier' ) %></label>
      <%= f.text_field :openid_identifier %>
    </div>
    <div class="form_row">
      <%= submit_tag t('people.edit.change_openid'), :class => "button" %>
    </div>
    <input type="hidden" name="type" value="openid_edit" />

  <% end %>
<%- end -%>

app/views/people/groups.html.erb
<%= column_div :type => :primary do -%>
  <h2><%= (params[:action] == 'admin_groups' ? "Admin " : "" ) + "Groups" %> <%= t('for') %> <%= h @person.display_name %></h2>

  <% unless @groups.empty? -%>
    <ul class="list people">
      <%= render :partial => @groups %>
    </ul>
  <% else %>
    <h3><%= t('people.groups.no_groups') %></h3>
  <% end -%>
  
  <%- if params[:action] == 'admin_groups' -%>
    <%= link_to t('people.groups.new_group'), new_group_path() %>
  <%- end -%>
  
<%- end -%>

<%= column_div :type => :secondary do -%>
  <%= render :partial => 'searches/box' %>
<%- end -%>

app/views/people/new.html.erb
<%= column_div :type => :primary do -%>
  <%- if global_prefs.app_name.blank? -%>
  <h2><%= t('people.new.header') %></h2>
  <%- else -%>
  <h2><%= t('people.new.header') %> <%= t('for') %> <%= global_prefs.app_name %></h2>
  <%- end -%>

  <%= error_messages_for :person %>
  <%= display global_prefs.registration_intro %>
  <%= form_for @person do |f| -%>

  <div class="form_row">
    <label for="language"><%= t('people._language.language') %></label>
    <%= f.select :language, [[t('people._language.english'),'en'],[t('people._language.spanish'),'es'],[t('people._language.french'),'fr'],[t('people._language.greek'),'gr']], {:selected => params[:locale]}, {:onchange => "document.location='/signup?locale=' + this.value"} %>
  </div>
  <fieldset id="creds">
<span id="standard">
  <div class="form_row">
    <label for="email">
      <%= t('people.new.email_address') %>
      <span class="small">(<%= t('people.new.never_made_public') %><%= t('people.new.comma_will_be_verified') if global_prefs.email_verifications? %>)
      </span>
    </label>
    <%= f.email_field :email %>
    <%= set_focus_to "person_email" %>  
  </div>

  <div class="form_row">
    <label for="name"><%= t('people.new.name') %> 
      <span class="small"><%= t('people.new.will_be_displayed') %></span></label>
    <%= f.text_field :name, :maxlength => Person::MAX_NAME %>
  </div>

  <% if @person.openid_identifier.blank? %>
    <div class="form_row">
      <label for="password"><%= t('people.new.password') %></label>
      <%= f.password_field :password, :maxlength => Person::MAX_PASSWORD %>
    </div>

    <div class="form_row">
      <label for="password_confirmation"><%= t('people.new.confirm_password') %></label>
      <%= f.password_field :password_confirmation, 
                           :maxlength => Person::MAX_PASSWORD,
                           :value => "" %>
    </div>
  <%- end -%>
</span>

<span id="openid">
  <div class="form_row">
    <label for="openid_identifier"><%= t('people.new.openid_url') %></label>
    <%= f.text_field :openid_identifier %>
  </div>
</span>
</fieldset>

<div style="text-align: center; font-size: 12px; padding: 10px;">
    <span id="noscript" style="display:none;">
      <span id="openid_link"><a href="#" onclick="show_openid(); return false;"><%= t('people.new.or_signup_with_openid') %></a></span>
      <span id="standard_link"><a href="#" onclick="show_standard(); return false;"><%= t('people.new.back_to_regular_signup') %></a></span>
    </span>

</div>
  <div class="form_row full">
        <label for="person_categories"><%= t('people.new.which_services') %>
        </label>
        <%= render :partial => "shared/select_categories", :locals => { :model_name => 'person' } %>
  </div>
  
  <div class="form_row">
    <label for="person_description"><%= t('people.new.something_about_yourself') %>
    </label>

    <%- unless @preview.nil? -%>
      <%= display @preview %>
    <%- end -%>
    
    <%= f.text_area :description %>
  </div>  

  <div class="form_row full">
        <label for="person_categories"><%= t('people.new.neighborhood') %>
        </label>
        <%= render :partial => "shared/select_neighborhoods", :locals => { :model_name => 'person' } %>
  </div>

  <div class="form_row">
    <label for="zipcode"><%= t('people.new.zipcode') %></label>
    <%= f.text_field :zipcode %>
  </div>

  <div class="form_row">
    <%= f.check_box :org, :class => 'checkbox' %> <%= t('people.new.business_account') %>
  </div>
  
  <div class="form_row">
    <%= f.check_box :accept_agreement, :class => 'checkbox' %> <%= t('people.new.i_accept_the') %> <%= link_to t('people.new.member_agreement'), agreement_path, :target => '_blank', :class => 'small' %>
  </div>

  <div class="form_row">
    <%= submit_tag t('people.new.signup_button'), :class => "button" %>
  </div>

  <% end %>
<%- end -%>