config/routes.rb
Oscurrency::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :person_sessions
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :member_preferences
  resources :neighborhoods

  # XXX in 2.3.x, this was easier -> map.resources :transacts, :as => "transacts/:asset"
  get    "transacts(/:asset)(.:format)"          => "transacts#index",   :as => 'transacts'
  get    "transacts(/:asset)/new"      => "transacts#new",     :as => 'new_transact'
  get    "transacts(/:asset)/:id(.:format)"      => "transacts#show",    :as => 'transact'
  post   "transacts(/:asset)(.:format)"          => "transacts#create",  :as => 'transacts'
  #get    "transacts/[:asset]/:id/edit" => "transacts#edit",    :as => 'edit_transact'
  #put    "transacts/[:asset]/:id"      => "transacts#update",  :as => 'transact'
  delete "transacts(/:asset)/:id(.:format)"      => "transacts#destroy", :as => 'transact'

  resources :groups, :shallow => true do
    member do
      post :join
      post :leave
      get :exchanges
      get :members
      get :graphs
      get :photos
      post :new_photo
      post :save_photo
      delete :delete_photo
    end
    resources :memberships
    resources :reqs
    resources :offers
    resource :forum
  end

  resources :bids
  resources :reqs do
    member do 
      post :deactivate
    end
    resources :bids
  end

  resources :offers
  resources :categories

  resources :memberships do
    member do
      delete :unsuscribe
      post :suscribe
    end
  end

  resources :searches
  resources :activities
  resources :connections
  resources :photos
  resources :messages do
    collection do
      get :sent
      get :trash
      get :recipients
    end
    member do
      get :reply
      put :undestroy
    end
  end
  resources :people do
    member do
      get :verify_email
      get :su
      get :common_contacts
      get :groups
      get :admin_groups
    end
    resources :messages
    resources :accounts
    resources :exchanges
    resources :addresses
    resources :photos
    resources :connections
  end

  match 'people/verify/:id' => 'people#verify_email'

  resources :forums do
    resources :topics do
      resources :posts
    end
  end
  match '/signup' => 'people#new', :as => :signup
  match '/login' => 'person_sessions#new', :as => :login
  match '/logout' => 'person_sessions#destroy', :as => :logout
  match '/refreshblog' => 'feed_posts#refresh_blog', :as => :refreshblog
  match '/about' => 'home#about', :as => :about
  match '/practice' => 'home#practice', :as => :practice
  match '/steps' => 'home#steps', :as => :steps
  match '/questions' => 'home#questions', :as => :questions
  match '/contact' => 'home#contact', :as => :contact
  match '/agreement' => 'home#agreement', :as => :agreement
  resources :oauth_clients
  match '/oauth/authorize' => 'oauth#authorize', :as => :authorize
  match '/oauth/token' => 'oauth#token', :as => :token
  match '/oauth/request_token' => 'oauth#request_token', :as => :request_token
  match '/oauth/access_token' => 'oauth#access_token', :as => :access_token
  match '/oauth/test_request' => 'oauth#test_request', :as => :test_request
  match '/oauth/scopes' => 'transacts#scopes', :as => :scopes
  match '/oauth/revoke' => 'oauth#revoke', :as => :revoke
  match '/oauth' => 'oauth#index', :as => :oauth
  match '/about_user' => 'transacts#about_user', :as => :about_user
  match '/user_info' => 'transacts#user_info', :as => :user_info
  match '/wallet' => 'transacts#wallet', :as => :wallet
  match '/.well-known/host-meta' => 'home#host_meta', :as => :host_meta
  match '/home/show/:id' => 'home#show'
  root :to => 'home#index'
  match '/' => 'home#index', :as => :home
end

app/models/group.rb
require 'texticle/searchable'

class Group < ActiveRecord::Base
  include ActivityLogger
  extend PreferencesHelper
  
  validates_presence_of :name, :person_id
  attr_protected :mandatory

  has_one :forum
  has_many :reqs, :conditions => "biddable IS true", :order => "created_at DESC"
  has_many :offers, :order => "created_at DESC"
  has_many :photos, :dependent => :destroy, :order => "created_at"
  has_many :exchanges, :order => "created_at DESC"
  has_many :memberships, :dependent => :destroy
  has_many :people, :through => :memberships, 
    :conditions => "status = 0", :order => "name DESC"
  has_many :pending_request, :through => :memberships, :source => "person",
    :conditions => "status = 2", :order => "name DESC"
  
  belongs_to :owner, :class_name => "Person", :foreign_key => "person_id"
  
  has_many :activities, :as => :item, :dependent => :destroy

  validates_uniqueness_of :name
  validates_uniqueness_of :unit, :allow_nil => true
  validates_uniqueness_of :asset, :allow_nil => true
  validates_format_of :asset, :with => /^[-\.a-z0-9]+$/i, :allow_blank => true
  validate :changing_asset_name_only_allowed_if_empty
  after_create :create_owner_membership
  after_create :create_forum
  after_create :log_activity
  before_update :update_member_credit_limits
  
  extend Searchable(:name, :description)
  
  # GROUP modes
  PUBLIC = 0
  PRIVATE = 1
  
  def get_groups_modes
    modes = []
    modes << ["Public",PUBLIC]
    modes << ["Membership approval required",PRIVATE] unless default_group?
    return modes
  end

  def default_group?
    id == Group.global_prefs.default_group_id
  end
  
  class << self

    def name_sorted_and_paginated(page = 1)
      paginate(:page => page,
               :per_page => RASTER_PER_PAGE,
               :order => "name ASC")
    end

    def by_opentransact(asset)
      Group.find_by_asset(asset)
    end
  end

  def opentransact?
    !asset.nil?
  end

  def admins
    admins = memberships.with_role('admin').map {|m| m.person}
    admins << owner if admins.empty?
    admins
  end

  def public?
    self.mode == PUBLIC
  end
  
  def private?
    self.mode == PRIVATE
  end
  
  def owner?(person)
    self.owner == person
  end
  
  ## Photo helpers
  def photo
    # This should only have one entry, but be paranoid.
    photos.find_all_by_primary(true).first
  end

  # Return all the photos other than the primary one
  def other_photos
    photos.length > 1 ? photos - [photo] : []
  end

  def main_photo
    photo.nil? ? "g_default.png" : photo.public_filename
  end

  def thumbnail
    photo.nil? ? "g_default_thumbnail.png" : photo.public_filename(:thumbnail)
  end

  def icon
    photo.nil? ? "g_default_icon.png" : photo.public_filename(:icon)
  end

  def bounded_icon
    photo.nil? ? "g_default_icon.png" : photo.public_filename(:bounded_icon)
  end

  # Return the photos ordered by primary first, then by created_at.
  # They are already ordered by created_at as per the has_many association.
  def sorted_photos
    # The call to partition ensures that the primary photo comes first.
    # photos.partition(&:primary) => [[primary], [other one, another one]]
    # flatten yields [primary, other one, another one]
    @sorted_photos ||= photos.partition(&:primary).flatten
  end
  
  
  private

  def changing_asset_name_only_allowed_if_empty
    unless new_record?
      if asset_changed?
        unless asset_was.blank?
          errors.add(:asset, "cannot be changed unless it is empty")
        end
      end
    end
  end

  def create_owner_membership
    mem = Membership.new( :status => Membership::PENDING )
    mem.person = self.owner 
    mem.group = self
    mem.roles = ['admin']
    mem.save
    Membership.accept(mem.person,mem.group)
  end

  def update_member_credit_limits
    if default_credit_limit_changed?
      transaction do
        memberships.each do |m|
          m.account.update_attributes!(:credit_limit => default_credit_limit)
        end
      end
    end
  end

  def log_activity
    activity = Activity.create!(:item => self, :person => Person.find(self.person_id))
    add_activities(:activity => activity, :person => Person.find(self.person_id))
  end
  
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  #before_filter :login_or_oauth_required
  before_filter :login_required
  skip_before_filter :require_activation
  load_and_authorize_resource
  
  def index
    @body = "noajax"
    # XXX can't define abilities w/ blocks (accessible_by) http://github.com/ryanb/cancan/wiki/Upgrading-to-1.4
    @groups = Group.name_sorted_and_paginated(params[:page])

    respond_to do |format|
      format.html
    end
  end

  def show
    membership_display

    respond_to do |format|
      format.html do
        @forum = @group.forum
        @topics = Topic.find_recently_active(@forum, params[:page]) 
        @reqs = Req.custom_search(nil,
                           @group, 
                           active=true,
                           1, # params[:page] 
                           AJAX_POSTS_PER_PAGE,
                           nil
                           )
        @offers = Offer.custom_search(nil,
                               @group,
                               active=true,
                               1, #params[:page]
                               AJAX_POSTS_PER_PAGE,
                               nil
                               )
        @exchanges = @group.exchanges.paginate(:page => params[:page], :per_page => AJAX_POSTS_PER_PAGE)
        @memberships = @group.memberships.active.paginate(:page => params[:page],
                                              :conditions => ['status = ?', Membership::ACCEPTED],
                                              :order => 'memberships.created_at DESC',
                                              :include => :person,
                                              :per_page => AJAX_POSTS_PER_PAGE)
      end
      format.js
      format.xml { render :xml => @group.to_xml(:methods => [:icon,:thumbnail], :only => [:id,:name,:description,:mode,:person_id,:created_at,:updated_at,:unit,:icon,:thumbnail]) }
    end

  end

  def new
    @photo = Photo.new
    respond_to do |format|
      format.html
    end
  end

  def edit
  end

  def create
    @group.owner = current_person

    respond_to do |format|
      if @group.save
        flash[:success] = t('success_group_created')
        format.html { redirect_to(group_path(@group)) }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @group.update_attributes(params[:group])
        flash[:notice] = t('notice_group_updated')
        format.html { redirect_to(group_path(@group)) }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def destroy
    @group.destroy

    respond_to do |format|
      flash[:success] = t('success_group_deleted')
      format.html { redirect_to(groups_path) }
    end
  end
 
  def exchanges
    @exchanges = @group.exchanges.paginate(:page => params[:page], :per_page => AJAX_POSTS_PER_PAGE)
    respond_to do |format|
      format.js
    end
  end

  def members
    @body = "noajax"
    @memberships = @group.memberships.paginate(:page => params[:page],
                                          :conditions => ['status = ?', Membership::ACCEPTED],
                                          :include => :person,
                                          :per_page => RASTER_PER_PAGE)

    @pending = @group.pending_request.paginate(:page => params[:page],
                                          :per_page => RASTER_PER_PAGE)
    respond_to do |format|
      format.html
    end
  end

  def graphs
    @num_months = 6
    respond_to do |format|
      format.js
    end
  end

  def photos
    #@group = Group.find(params[:id])
    @photos = @group.photos
    respond_to do |format|
      format.html
    end
  end
  
  def new_photo
    respond_to do |format|
      format.html
    end
  end
  
  def save_photo
    #group = Group.find(params[:id])
    if params[:photo].nil?
      # This is mainly to prevent exceptions on iPhones.
      flash[:error] = t('error_browser_upload_fail')
      redirect_to(edit_group_path(@group)) and return
    end
    if params[:commit] == "Cancel"
      flash[:notice] = t('notice_upload_canceled')
      redirect_to(edit_group_path(@group)) and return
    end
    
    group_data = { :group => @group,
                    :primary => @group.photos.empty? }
    @photo = Photo.new(params[:photo].merge(group_data))
    
    respond_to do |format|
      if @photo.save
        flash[:success] = t('success_photo_uploaded')
        if @group.owner == current_person
          format.html { redirect_to(edit_group_path(@group)) }
        else
          format.html { redirect_to(group_path(@group)) }
        end
      else
        format.html { render :action => "new_photo" }
      end
    end
  end
  
  def delete_photo
    @group = Group.find(params[:id])
    @photo = Photo.find(params[:photo_id])
    @photo.destroy
    flash[:success] = t('success_photo_deleted_for_group') + " '#{@group.name}'"
    respond_to do |format|
      format.html { redirect_to(edit_group_path(@group)) }
    end
  end
  
  protected

  def membership
    @membership ||= Membership.mem(current_person,@group)
  end

  def membership_display
    if membership
      @add_membership_display = 'hide'
      @membership_display = ''
      @membership_id = membership.id
    else
      @add_membership_display = ''
      @membership_display = 'hide'
      @membership_id = ""
    end
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  
  def group_owner?(person,group)
    person == group.owner
  end
  
  # Return a group's image link.
  # The default is to display the group's icon linked to the profile.
  def group_image_link(group, options = {})
    link = options[:link] || group
    image = options[:image] || :icon
    image_options = { :title => h(group.name), :alt => h(group.name) }
    unless options[:image_options].nil?
      image_options.merge!(options[:image_options]) 
    end
    link_options =  { :title => h(group.name) }
    unless options[:link_options].nil?                    
      link_options.merge!(options[:link_options])
    end
    content = image_tag(group.send(image), image_options)
    # This is a hack needed for the way the designer handled rastered images
    # (with a 'vcard' class).
    if options[:vcard]
      content = %(#{content}#{content_tag(:span, h(group.name), 
                                                 :class => "fn" )})
    end
    link_to(content, link, link_options)
  end
  
  def group_link(group)
    link_to(h(group.name), group_path(group))
  end

  def delete_membership_link(person,group)
    membership = Membership.mem(person,group)
    if membership
      membership_path(membership)
    else
      "#"
    end
  end
end

app/views/groups/_group.html.erb
<li class="vcard person">
  <div class="profile-image">
    <%= group_image_link group, :class => "photo", :image => :thumbnail %>
  </div>
  <p><%= link_to(group.name, group, :class => "url fn") %></p>
  <%= display(group.description, :class => "note") %>
</li>

app/views/groups/_membership.html.erb
<span id="membership_wrapper">
  <span class="membership_id"><span class="value"><%= @membership_id %></span></span>
  <li class="add_to_memberships <%= @add_membership_display %>">
  <%= link_to t('groups.show.join_group'),group_memberships_path(@group), {:id => 'join_group'} %>
  </li>
  <li class="add_to_memberships <%= @membership_display %>">
    <%= t('groups.show.you_are_a_member_of') %> <strong><%= h @group.name%></strong>
    <br />
    <% unless @group.default_group? %>
      <% if Membership.exist?(current_person, @group) %>
        (<%= link_to t('groups.show.leave_group'),delete_membership_link(current_person,@group), {:id => 'leave_group'} %>) 
      <% end %>
    <% end %>
  </li>
  <%= waiting_image %>
</span>

app/views/groups/_toolbox.html.erb
        <div class="toolbox">
          <%= image_tag @group.main_photo, :class => "profile-image photo",
                                        :alt => h(@group.name) %>
            <ul class="tools">
            <%- if @membership.try(:person).try(:org) %>
              <li><span class="label"><%= t('groups.show.contact') %></span>: <%= @membership.person.name %></li>
            <%- end %>
            <%- if @group.adhoc_currency? %>
              <li>
                <%= link_to t('home.index.community_exchanges_graph'), graphs_group_path(@group), :class => "show-follow" %>
              </li>
              <%- if @membership %>
                <%- if @membership.account.credit_limit %>
                  <li><%= t('groups.show.your_credit_limit') %> <%= @membership.account.credit_limit %> <%= @group.unit %></li>
                <%- end -%>
              <%- else -%>
                <%- if @group.default_credit_limit %>
                  <li><%= t('groups.show.default_credit_limit') %> <%= @group.default_credit_limit %> <%= @group.unit %></li>
                <%- end -%>
              <%- end -%>
            <%- end -%>
            <%- if @membership %>
              <% if @group.asset %>
              <li>
                <%= link_to t('groups.show.your_activity'), transacts_path(@group.asset), :target => '_blank' %>
              </li>
              <% end %>
              <li><%= link_to t('home.index.edit_your_preferences'), edit_member_preference_path(@membership.member_preference), :class => "show-follow" %></li>
            <%- end -%>
            <%- if Membership.pending?(current_person, @group) -%>
              <li>
                <%= t('groups.show.you_have_requested_to_be_a_member_of') %> <strong><%= h @group.name %></strong>
              </li>
            <%- end -%>
            <%- if group_owner?(current_person,@group) -%>
              <li>
                <%= t('groups.show.you_are_group_admin') %>
                <%= link_to t('groups.show.delete_it'), group_path(@group), :confirm => t('are_you_sure'), :method => :delete %>
              </li>
              <li>
                <%= t('groups.show.mode') %> <%= @group.get_groups_modes[@group.mode][0] %>
              </li>
              <% if @group.asset %>
              <li>
                <%= t('groups.show.asset_name') %> <%= link_to @group.asset, transacts_path(@group.asset), :target => '_blank' %>
              </li>
              <% end %>
            <%- end -%>
            <%= render :partial => 'membership' %>
          </ul>
        </div>

app/views/groups/edit.html.erb
<%= column_div :type => :primary do -%>
  <h2><%= t('groups.edit.header') %></h2>
  <div id="profile_edit">

  <%= form_for(@group) do |f| %>
    <%= f.error_messages %>

    <div class="form_row">
      <label for="name"><%= t('groups.edit.name') %></label>
      <%= f.text_field :name %>
    </div>

<%- if @group.adhoc_currency? -%>
    <div class="form_row">
      <label for="unit"><%= t('groups.edit.currency_unit_plural') %></label>
      <%= f.text_field :unit %>
    </div>

    <div class="form_row">
      <label for="asset"><%= t('groups.edit.asset') %></label>
      <%= f.text_field :asset, :disabled => !@group.asset.nil? %>
    </div>

    <div class="form_row">
      <label for="default_credit_limit"><%= t('groups.edit.default_credit_limit') %></label>
      <%= f.text_field :default_credit_limit, :size => 5 %>
    </div>
<%- end -%>

    <div class="form_row">
      <label for="description"><%= t('groups.edit.description') %></label>
      <%= f.text_area :description %>
    </div>

    <div class="form_row">
      <label for="mode"><% t('groups.edit.mode') %></label>
      <%= f.select :mode, @group.get_groups_modes %>
    </div>  
    
    <div class="form_row">
      <%= f.submit t('button_update'), :class => "button" %>
    </div>
  <% end %>
  
  
  <h3><%= t('groups.edit.photos') %></h3>
  
    <% if @group.photos.empty? %>
      <%= image_tag @group.thumbnail %>
    <% else %>
    <table>
      <% @group.sorted_photos.collect_every(N_COLUMNS) do |row| %>
      <tr>
      <% row.each do |photo| %>
        <td  style="padding-left: 1em;">
          <%= image_tag photo.public_filename(:thumbnail) %>
        </td>
      <% end %>
      </tr>
      <tr>
        <% row.each do |photo| %>
        <td style="padding-left: 1em;">
          <% if photo.primary? %>
            <%= t('groups.edit.primary') %>
          <% else %>
            <%= link_to "select", photo_path(photo),
                                          :method => :put %>
          <% end %>
          |
          <%= link_to image_tag("icons/close.gif"), 
                      delete_photo_group_path(@group)+"?photo_id=#{photo.id}",
                      :method => :delete %>
        </td>
        <% end %>
      </tr>
      <% end %>
    </table>
    <% end %>
    <br />
    <%= button_to t('groups.edit.add_a_photo'), new_photo_group_path(@group), :class => "button" %>
  </div>

<%- end -%>
<%= column_div :type => :secondary do -%>
  <h2>Forum</h2>
  <p>
  <%= link_to "Edit Forum Preferences", edit_forum_path(@group.forum) %>
  </p>
  <h2>Members</h2>
  <p>
    <%= link_to "Edit Member Roles", members_group_path(@group) %>
  </p>
<%- end -%>

app/views/groups/members.html.erb
<%= column_div :type => :primary do -%>
  <h2><%= link_to h(@group.name), group_path(@group) %></h2>
  
  <% unless @pending.empty? -%>
    <h3><%= t('groups.members.pending_request') %></h3>
    <%= will_paginate(@pending) %>
    <ul class="grid contacts medium">
      <%- @pending.each do |contact| -%>
        <li class="contact">
          <%= image_link contact, :image_options => { :class => "photo" },
                                  :link_options => { :class => "url" },
                                  :image => :bounded_icon %>
          <% if @group.owner?(current_person) %>
            <div class="accept_or_cancel_membership">
                <%= link_to image_tag("icons/remove.gif"), 
                  unsuscribe_membership_path(contact.memberships.find(:first, :conditions => ['group_id = ?',@group])), 
                  :method => "delete", :title => t('groups.members.cancel_membership'), 
                :confirm => t('groups.members.confirm')  %>
                <%= link_to image_tag("icons/add.gif"), 
                  suscribe_membership_path(contact.memberships.find(:first, :conditions => ['group_id = ?',@group])), 
                  :method => "post", :title => t('groups.members.accept_membership') %>
            </div>
          <% end %>
        </li>
      <%- end -%>

    </ul>
    <%= will_paginate(@pending) %>
  <% end -%>

  <h3><%= t('groups.members.header') %></h3>

  <% unless @memberships.empty? -%>
    <%= will_paginate(@memberships) %>
    <ul class="grid contacts medium">
      <%- @memberships.each do |membership| -%>
        <% contact = membership.person %>
        <li class="contact">
          <%= image_link contact, :image_options => { :class => "photo" },
                                  :link_options => { :class => "url" },
                                  :image => :bounded_icon %>
          <% if can? :unsuscribe, membership %>
            <div class="cancel_membership">
                <%= link_to image_tag("icons/remove.gif"), 
                  unsuscribe_membership_path(membership), 
                  :method => "delete",
                  :title => t('groups.members.cancel_membership'),
                  :confirm => t('groups.members.confirm') %>
            </div>
          <%- end -%>
          <% if can? :update, membership %>
            <div class="edit_roles">
              <%= link_to image_tag("icons/edit.gif"), edit_membership_path(membership), :title => 'Edit member roles' %>
            </div>
          <% end %>
        </li>
      <%- end -%>

    </ul>
    <%= will_paginate(@memberships) %>
  <% else %>
    <h3><%= t('groups.members.no_members_yet') %></h3>
  <% end -%>

  <h3><%= t('groups.members.admins') %></h3>
  <ul class="grid contacts medium">
    <%- @group.admins.each do |admin| -%>
      <li class="contact">
      <%= image_link admin, :image_options => { :class => "photo" },
                            :link_options => { :class => "url" },
                            :image => :bounded_icon %>
      </li>
    <%- end -%>
  </ul>

  <h3><%= t('groups.members.created_by') %></h3>
  <ul class="grid contacts medium">
    <li class="contact">
      <%= image_link @group.owner, :image_options => { :class => "photo" },
                              :link_options => { :class => "url" },
                              :image => :bounded_icon %>
    </li>
  </ul>

<%- end -%>

app/views/groups/new.html.erb
<script type="text/javascript">
  function toggle_currency_unit(el) {
    unit_el = document.getElementById('group_unit');
    asset_el = document.getElementById('group_asset');
    credit_limit_el = document.getElementById('group_default_credit_limit');
    if(el.checked)
    {
      unit_el.disabled = false;
      asset_el.disabled = false;
      credit_limit_el.disabled = false;
    }
    else
    {
      unit_el.value = '';
      unit_el.disabled = true;
      asset_el.value = '';
      asset_el.disabled = true;
      credit_limit_el.value = '';
      credit_limit_el.disabled = true;
    }
  }
</script>
<%= column_div :type => :primary do -%>
  <h2><%= t('groups.new.header') %></h2>

  <%= form_for(@group) do |f| %>
    <%= f.error_messages %>

    <div class="form_row">
      <label for="name"><%= t('groups.new.name') %></label>
      <%= f.text_field :name %>
    </div>

    <div class="form_row">
      <label for="adhoc_currency" class="checkbox"><%= t('groups.new.adhoc_currency') %></label>
      <%= f.check_box :adhoc_currency, :onclick => "toggle_currency_unit(this);" %>
    </div>
    <fieldset id="currency_fields">
    <div class="form_row">
      <label for="unit"><%= t('groups.new.currency_unit_plural') %></label>
      <%= f.text_field :unit, :disabled => true %>
    </div>

    <div class="form_row">
      <label for="asset"><%= t('groups.new.asset') %></label>
      <%= f.text_field :asset, :size => 8, :disabled => true %>
    </div>

    <div class="form_row">
      <label for="default_credit_limit"><%= t('groups.new.default_credit_limit') %></label>
      <%= f.text_field :default_credit_limit, :size => 5, :disabled => true %>
    </div>
    </fieldset>
    <div class="form_row">
      <label for="description"><%= t('groups.new.description') %></label>
      <%= f.text_area :description %>
    </div>

    <div class="form_row">
      <label for="mode"><%= t('groups.new.mode') %></label>
      <%= f.select :mode, @group.get_groups_modes %>
    </div>
    
    <div class="form_row">
      <%= f.submit t('button_create'), :class => "button" %>
    </div>
  <% end %>
<%- end -%>

app/views/groups/new_photo.html.erb
<h2><%= t('groups.new_photo.header') %></h2>
<%= error_messages_for :photo %>

<%= form_for @photo, :url => {:action => "save_photo"}, :html => { :multipart => true } do |f| -%>

  <div class="form_field">
    <label for="photo"><%= t('groups.new_photo.upload_a_photo') %></label>
    <%= f.file_field :uploaded_data %>
  </div>
  <div class="form_field">
    <%= submit_tag t('button_upload'), :class => "button" %>
    <%= f.submit t('button_cancel'), :id => "cancel", :class => "button" %>
  </div>
<% end -%>