config/routes.rb
Oscurrency::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :person_sessions
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :member_preferences
  resources :neighborhoods

  # XXX in 2.3.x, this was easier -> map.resources :transacts, :as => "transacts/:asset"
  get    "transacts(/:asset)(.:format)"          => "transacts#index",   :as => 'transacts'
  get    "transacts(/:asset)/new"      => "transacts#new",     :as => 'new_transact'
  get    "transacts(/:asset)/:id(.:format)"      => "transacts#show",    :as => 'transact'
  post   "transacts(/:asset)(.:format)"          => "transacts#create",  :as => 'transacts'
  #get    "transacts/[:asset]/:id/edit" => "transacts#edit",    :as => 'edit_transact'
  #put    "transacts/[:asset]/:id"      => "transacts#update",  :as => 'transact'
  delete "transacts(/:asset)/:id(.:format)"      => "transacts#destroy", :as => 'transact'

  resources :groups, :shallow => true do
    member do
      post :join
      post :leave
      get :exchanges
      get :members
      get :graphs
      get :photos
      post :new_photo
      post :save_photo
      delete :delete_photo
    end
    resources :memberships
    resources :reqs
    resources :offers
    resource :forum
  end

  resources :bids
  resources :reqs do
    member do 
      post :deactivate
    end
    resources :bids
  end

  resources :offers
  resources :categories

  resources :memberships do
    member do
      delete :unsuscribe
      post :suscribe
    end
  end

  resources :searches
  resources :activities
  resources :connections
  resources :photos
  resources :messages do
    collection do
      get :sent
      get :trash
      get :recipients
    end
    member do
      get :reply
      put :undestroy
    end
  end
  resources :people do
    member do
      get :verify_email
      get :su
      get :common_contacts
      get :groups
      get :admin_groups
    end
    resources :messages
    resources :accounts
    resources :exchanges
    resources :addresses
    resources :photos
    resources :connections
  end

  match 'people/verify/:id' => 'people#verify_email'

  resources :forums do
    resources :topics do
      resources :posts
    end
  end
  match '/signup' => 'people#new', :as => :signup
  match '/login' => 'person_sessions#new', :as => :login
  match '/logout' => 'person_sessions#destroy', :as => :logout
  match '/refreshblog' => 'feed_posts#refresh_blog', :as => :refreshblog
  match '/about' => 'home#about', :as => :about
  match '/practice' => 'home#practice', :as => :practice
  match '/steps' => 'home#steps', :as => :steps
  match '/questions' => 'home#questions', :as => :questions
  match '/contact' => 'home#contact', :as => :contact
  match '/agreement' => 'home#agreement', :as => :agreement
  resources :oauth_clients
  match '/oauth/authorize' => 'oauth#authorize', :as => :authorize
  match '/oauth/token' => 'oauth#token', :as => :token
  match '/oauth/request_token' => 'oauth#request_token', :as => :request_token
  match '/oauth/access_token' => 'oauth#access_token', :as => :access_token
  match '/oauth/test_request' => 'oauth#test_request', :as => :test_request
  match '/oauth/scopes' => 'transacts#scopes', :as => :scopes
  match '/oauth/revoke' => 'oauth#revoke', :as => :revoke
  match '/oauth' => 'oauth#index', :as => :oauth
  match '/about_user' => 'transacts#about_user', :as => :about_user
  match '/user_info' => 'transacts#user_info', :as => :user_info
  match '/wallet' => 'transacts#wallet', :as => :wallet
  match '/.well-known/host-meta' => 'home#host_meta', :as => :host_meta
  match '/home/show/:id' => 'home#show'
  root :to => 'home#index'
  match '/' => 'home#index', :as => :home
end

app/models/req.rb
require 'texticle/searchable'

class Req < ActiveRecord::Base
  include ActivityLogger
  include AnnouncementBase
  extend PreferencesHelper

  extend Searchable(:name, :description)

  scope :active, :conditions => ["active IS true AND due_date >= ?", DateTime.now]
  scope :biddable, where("biddable = ?", true)
  scope :current, lambda { where("due_date >= ?", DateTime.now) }
  scope :without_approved_bid,
    joins("LEFT JOIN bids AS approved_bids ON approved_bids.req_id = reqs.id AND approved_bids.state = 'approved'").
    where("approved_bids.id IS NULL")

  has_many :workers, :through => :categories, :source => :people
  has_many :bids, :order => 'created_at DESC', :dependent => :destroy
  has_many :accepted_bids, :class_name => "Bid", :conditions => "accepted_at IS NOT NULL"
  has_many :completed_bids, :class_name => "Bid", :conditions => "completed_at IS NOT NULL"
  has_many :committed_bids, :class_name => "Bid", :conditions => "committed_at IS NOT NULL"
  has_many :approved_bids, :class_name => "Bid", :conditions => "approved_at IS NOT NULL"

  attr_accessor :ability
  attr_protected :ability
  attr_readonly :estimated_hours

  validates :due_date, :presence => true

  before_create :make_active, :if => :biddable
  after_create :send_req_notifications, :if => :notifications

  class << self

    def current_and_active(page=1)
      self.biddable.current.without_approved_bid.page(page).order('created_at DESC')
    end

    def all_active(page=1)
      self.biddable.page(page).order('created_at DESC')
    end

  end

  def considered_active?
    active? && (due_date > DateTime.now)
  end

  def deactivate
    update_attributes(:active => false)
  end

  def has_accepted_bid?
    return bids.any? &:accepted_at if bids.loaded?
    accepted_bids.exists?
  end

  def has_completed?
    return bids.any? &:completed_at if bids.loaded?
    completed_bids.exists?
  end

  def has_commitment?
    return bids.any? &:committed_at if bids.loaded?
    committed_bids.exists?
  end

  def has_approved?
    return bids.any? &:approved_at if bids.loaded?
    approved_bids.exists?
  end

  def log_activity
    super if active?
  end

  def notifiable_workers
    workers.active.connection_notifications
  end

  def should_send_notifications?
    active and Req.global_prefs.can_send_email? and Req.global_prefs.email_notifications?
  end

  # private

  def make_active
    self.active = true
  end

  def send_req_notifications
    notifiable_workers.each do |worker|
      after_transaction { PersonMailerQueue.req_notification(self, worker) }
    end if should_send_notifications?
  end

end

app/controllers/reqs_controller.rb
class ReqsController < ApplicationController

  respond_to :html, :xml, :json, :js

  skip_before_filter :require_activation, :only => [:show, :index]
  before_filter :login_required, :except => [:show, :index]
  before_filter :login_or_oauth_required, :only => [:show, :index]
  load_resource :group
  load_and_authorize_resource :req, :through => :group, :shallow => true
  before_filter :correct_person_and_no_accept_required, :only => [ :edit, :update ]
  before_filter :correct_person_and_no_commitment_required, :only => [ :destroy ]

  # GET /reqs
  # GET /reqs.xml
  def index
    @selected_category = params[:category_id].nil? ? nil : Category.find(params[:category_id])

    @reqs = Req.custom_search(@selected_neighborhood || @selected_category,
                              @group,
                              active=params[:scope].nil?, # if a scope is not passed, just return actives
                              params[:page],
                              AJAX_POSTS_PER_PAGE,
                              params[:search]
                              )
    respond_with @reqs
  end

  # GET /reqs/1
  # GET /reqs/1.xml
  def show
    @req = Req.find(params[:id])
    @bid = Bid.new
    @bid.estimated_hours = @req.estimated_hours

    unless @req.group.nil?
      if logged_in?
        unless Membership.exist?(current_person,@req.group)
          flash[:notice] = t('notice_bid_requires_membership')
        end
      end
    end

    respond_with @req
  end

  # GET /reqs/new
  # GET /reqs/new.xml
  def new
    @all_categories = Category.by_long_name
    @all_neighborhoods = Neighborhood.by_long_name
    @selected_neighborhoods = current_person.neighborhoods

    respond_to do |format|
      format.js
      format.xml  { render :xml => @req }
    end
  end

  # GET /reqs/1/edit
  def edit
    @req = Req.find(params[:id])
    @group = @req.group
    @all_categories = Category.by_long_name
    @all_neighborhoods = Neighborhood.by_long_name

    respond_to do |format|
      format.js
    end
  end

  # POST /reqs
  # POST /reqs.xml
  def create
    #@req = Req.new(params[:req])
    @req.group = @group
    @req.person = current_person

    @all_categories = Category.by_long_name
    @all_neighborhoods = Neighborhood.by_long_name
    @reqs = Req.custom_search(nil,@group,active=true,page=1,AJAX_POSTS_PER_PAGE,nil)

    flash[:notice] = t('success_request_created') if @req.save
    respond_with @req
  end

  # PUT /reqs/1
  # PUT /reqs/1.xml
  def update
    @req = Req.find(params[:id])
    @group = @req.group
    @all_categories = Category.by_long_name
    @all_neighborhoods = Neighborhood.by_long_name

    respond_to do |format|
      if @req.update_attributes(params[:req])
        flash[:notice] = t('notice_request_updated')
        @reqs = Req.custom_search(nil,@group,active=true,page=1,AJAX_POSTS_PER_PAGE,nil)
        format.html { redirect_to(@req) }
        format.js
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.js { render :action => "edit" }
        format.xml  { render :xml => @req.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /reqs/1
  # DELETE /reqs/1.xml
  def destroy
    @req = Req.find(params[:id])
    if can?(:destroy, @req)
      flash[:notice] = t('success_request_destroyed')
      @req.destroy
    else
      flash[:error] = t('error_request_cannot_be_deleted')
    end

    respond_to do |format|
      format.html { redirect_to(reqs_url) }
      format.xml  { head :ok }
      format.js
    end
  end

  def deactivate
    @req = Req.find(params[:id])
    if can?(:deactivate, @req)
      flash[:notice] = t('success_request_deactivated')
      @req.deactivate
    end
    respond_to do |format|
      format.js
    end
  end

  # private

  def correct_person_and_no_accept_required
    request = Req.find(params[:id])
    redirect_to home_url unless request.person == current_person
    redirect_to home_url if request.has_accepted_bid?
  end

  def correct_person_and_no_commitment_required
    request = Req.find(params[:id])
    redirect_to home_url if request.has_commitment? || request.has_approved?
  end
end

app/helpers/reqs_helper.rb
module ReqsHelper
  def active_reqs_class
    if params[:scope]
      "toggle-active-reqs"
    else
      "toggle-active-reqs filter_selected"
    end
  end

  def all_reqs_class
    if params[:scope]
      "toggle-all-reqs filter_selected"
    else
      "toggle-all-reqs"
    end
  end

  def accepted_messages(req)
    req.accepted_bids.map {|bid| "Accepted bid from #{person_link bid.person} at #{time_ago_in_words(bid.accepted_at)} #{t('ago')}"}
  end

  def commitment_messages(req)
    req.committed_bids.map {|bid| "Commitment by #{person_link bid.person} made #{time_ago_in_words(bid.committed_at)} #{t('ago')}"}
  end

  def completed_messages(req)
    req.completed_bids.map {|bid| "Marked completed by #{person_link bid.person} #{time_ago_in_words(bid.completed_at)} #{t('ago')}"}
  end

  def approved_messages(req)
    req.approved_bids.map {|bid| "Confirmed completed by #{person_link req.person} #{time_ago_in_words(bid.approved_at)} #{t('ago')}"}
  end

  def formatted_req_categories(categories)
    (categories.map(&:to_s).join("<br>") + "<br>").html_safe
  end
end

app/views/reqs/_edit_req.html.erb
<h2><%= t('reqs.edit.header') %></h2>
<%= form_for @req, :html => {:id => 'edit_req'} do |f| %>
  <%= render :partial => 'form_fields', :locals => {:f => f, :estimate_disabled => true} %>
  <div class="form_row">
    <%= f.submit t('button_update') %><%= waiting_image %>
  </div>
<% end %>

app/views/reqs/_new_req.html.erb
<h2><%= t('reqs.new.header') %></h2>
<%= form_for :req, :url => group_reqs_path(@group), :html => {:id => 'new_req'} do |f| %>
  <%= render :partial => 'form_fields', :locals => {:f => f, :estimate_disabled => false} %>
  <div id="providersDisplay" style="height: 95px;" class="form_row full"><label><%= t('reqs.new.people_to_be_notified') %>:</label><div id="followMe"></div></div>
  <div class="form_row">
    <label for="notifications" class="checkbox"><%= t('reqs.new.notify_members_email') %></label>
    <%= check_box_tag 'req[notifications]', '1', true %>
  </div>
  <div class="form_row">
    <%= f.submit t('button_create') %><%= waiting_image %>
  </div>
<% end %>

app/views/reqs/_req.html.erb
<div class="req req_id_<%= req.id %>">
  <a name="req_<%= req.id %>"></a>
  <div class="profile-image">
    <%= image_link req.person, :image => :thumbnail %>
    <%= image_tag "icons/new.gif", :class => "icon", :alt => "Request" %>
  </div>
  <p>
  <%= link_to h(req.name), req, :class => "show-follow" %> (<%= h req.estimated_hours %> <%= h req.unit %>)
  <%= t('reqs.partial.due') %>: <%= relative_time_ago_in_words(req.due_date) %>
  </p>
    <%= display formatted_req_categories(req.long_categories), :class => "meta" %>
  <p>
    <%= markdown((full rescue false) ? req.description : first_n_words(req.description)) %>
  </p>
  <p class="meta">
    <%= render :partial => "shared/bid_message", :collection => approved_messages(req) %>
    <%= render :partial => "shared/bid_message", :collection => completed_messages(req) %>
    <%= render :partial => "shared/bid_message", :collection => commitment_messages(req) %>
    <%= render :partial => "shared/bid_message", :collection => accepted_messages(req) %>
    <%= t('reqs.partial.createdby') %> <%= person_link req.person %>
    <%= time_ago_in_words(req.created_at) %> <%= t('ago') %>
    <% if can?(:update, req) -%>
      | <%= link_to t('button_edit'), edit_req_path(req), :class => 'show-follow' %>
    <% end -%>
    <% if req.biddable? %>
      <% if can?(:destroy, req) -%>
        | <%= link_to t('button_delete'), req, :class => 'delete_req' %>
      <% end -%>
      <% if can?(:deactivate, req) && req.considered_active? -%>
        | <%= link_to t('button_deactivate'), deactivate_req_path(req), :class => 'deactivate_req' %>
      <% end -%>
    <% end -%>
    <br>
    <% if !current_person.address.nil? && !req.person.address.nil? && !current_person?(req.person) -%>
      <%= number_with_precision(req.person.address.distance_to(current_person.address), :precision => 1).to_s %> <%= t('miles_away') %>
    <% end -%>
  </p>
</div>

app/views/reqs/_req_full.html.erb
  <h2><%= h @req.name %><%= waiting_image %></h2>
  <ul class="list full">
    <%= render :partial => @req, :locals => {:full => true} %>
  </ul>
  <% if @req.active? %>
    <%= render :partial => '/reqs/bids' %>
  <%- end -%>

app/views/reqs/create.js.erb
window.location.hash = "#requests";
$('#reqs_canvas').html('<%= escape_javascript(render :partial => 'reqs_canvas') %>');
$('#reqs_canvas').linkify();
<%= render :partial => '/shared/flash_messages', :locals => {:canvas_id => 'reqs_canvas'} %>